services:
  - type: web
    name: imtihon-bot
    runtime: python
    plan: free
    buildCommand: ""
    startCommand: "python main.py"
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: DATA_DIR
        value: /var/data
      - key: DB_PATH
        value: /var/data/test_bot.db
      - key: UPLOADS_DIR
        value: /var/data/uploads
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: PYTHONIOENCODING
        value: utf-8
    disk:
      name: data-disk
      mountPath: /var/data
      sizeGB: 1
